spring:
  cloud:
    gateway:
      globalcors:
        crosConfigurations:
          "[/**]":
            allow-credentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: path_route_admin
          uri: lb://eshop-admin
          predicates:
            - Path=/admin/**
        - id: path_route_wares
          uri: lb://eshop-wares
          predicates:
            - Path=/wares/**


